In [141]:
def cal_area(center_a,center_b,d,theta_1,theta_2,R):

    try :
        theta = theta_1 - theta_2

        point_1 = center_a +(center_b*center_a)/(R*tf.sin(theta_1))

        point_2 = center_a +(center_b*(center_a-d))/(R*tf.sin(theta_2))

        fan_shape = (1/2) * theta * (pow(R,2))

        triangle_1 = (1/2)  * (0-point_1) * (R*tf.sin(theta_1)+center_b)

        triangle_2 = (1/2)  * (d - point_2) * (R*tf.sin(theta_2)+center_b)

        triangle_3 = (1/2)  * (point_2 - point_1) * (0-center_b)

        area = fan_shape - triangle_1 + triangle_2 - triangle_3

    except :
        area = 0

    # print(f'theta_1: {math.degrees(theta_1)} theta_2: {math.degrees(theta_2)} theta: {math.degrees(theta)}')

    return area

In [142]:
# Import TensorFlow and NumPy
import tensorflow as tf
import numpy as np
import scipy as sp

# Set data type
DTYPE='float64'
tf.keras.backend.set_floatx(DTYPE)

# Define contact line velocity
# theta_0 : equilibrium contact angle
# theta_d : dynamic contact angle
def fun_contact_line_velocity( f_c,i_t,theta_0, theta_d ):
    one = tf.constant(1, dtype=tf.float64)
    return -f_c*i_t*(-tf.cos(theta_0)+tf.cos(theta_d))
# Set constants
pi = tf.constant(np.pi, dtype=tf.float64)
p_f_c = tf.constant(-2.02, dtype=tf.float64) # positive_friction_coefficient
n_f_c = tf.constant(-5.64, dtype=tf.float64) # nagative_friction_coefficient
i_t = tf.constant(7.6408/1000, dtype=tf.float64) #interfacial tension between the two liquids
d = tf.constant(0.321/1000, dtype=tf.float64) #gab

thetal_0 = tf.constant(np.deg2rad(94), dtype=tf.float64)
thetal_d = tf.constant(np.deg2rad(55), dtype=tf.float64)
thetar_0 = tf.constant(np.deg2rad(59),dtype=tf.float64)
thetar_d = tf.constant(np.deg2rad(109),dtype=tf.float64)

r_0 = tf.constant(np.deg2rad(109), dtype=tf.float64)
cneter_a = tf.constant(-0.0000566758, dtype=tf.float64)
cneter_b = tf.constant(-0.0006874250504951296, dtype=tf.float64)

theta1_0 = tf.constant(np.pi-np.deg2rad(94),dtype=tf.float64)
theta2_0 =  thetar_0

vl = tf.constant(-fun_contact_line_velocity(n_f_c ,i_t,thetal_0, thetal_d ),shape=(1,1) , dtype=tf.float64)
vr = tf.constant(-fun_contact_line_velocity(p_f_c ,i_t,thetar_0 , thetar_d ),shape=(1,1) , dtype=tf.float64)

# initial_data = [a0 ,b0,r0 ,theta_l0,theta_r0 ]
# cal_area_theta(center_a,center_b,d,theta_l,theta_r,R):
initial_data = [-0.0000566758,-0.0006874250504951296,.0009033011295732994,1.500983153589793,1.0874056000]
initial_area = tf.constant(5.375716695978319e-08,shape=(1,1) , dtype=tf.float64)
initial_data = tf.concat([cneter_a ,cneter_b ,r_0 ,theta1_0,theta2_0 ],axis=0)
initial_data = tf.reshape(initial_data,shape=(-1,5))
print(initial_data)
print(initial_area)
print(type(initial_area))
#thetar_d = tf.constant(initial_area, dtype=tf.float64)

# Define residual of the condition
def fun_r(yl_t , yr_t ,vl,vr,area_t ):
    return ((yl_t-vl) + (yr_t-vr)+area_t)

tf.Tensor(
[[-5.66758000e-05 -6.87425050e-04  1.90240888e+00  1.50098316e+00
   1.02974426e+00]], shape=(1, 5), dtype=float64)
tf.Tensor([[5.3757167e-08]], shape=(1, 1), dtype=float64)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [89]:
print(vr)
print(vl)

tf.Tensor(0.012974266236244947, shape=(), dtype=float64)
tf.Tensor(-0.027723860480927242, shape=(), dtype=float64)


In [46]:
import tensorflow as tf
import numpy as np

In [143]:
# time interval
time = [0.0,0.0280]
# start_time
start_time= tf.constant(time[0], shape=(1,1),dtype=DTYPE)
# last_time
end_time = tf.constant(time[1], shape=(1,1),dtype=DTYPE)

# Set random seed for reproducible results
tf.random.set_seed(0)

t_data = tf.random.uniform(shape=[1,1000],minval=0.0,maxval=0.0280, dtype=DTYPE)
t_data = tf.reshape(t_data,shape=(-1,1))

#t_data = tf.linspace(0.0,0.0280,100)
#t_data = tf.reshape(t_data,shape=(-1,1))
#
# t_data =tf.concat([start_time,t_data],axis=0)
# t_data = tf.concat([t_data,end_time],axis=0)
t_data = tf.constant(t_data,dtype=DTYPE)
t_data = tf.sort(t_data,axis=0)
print(t_data)

tf.Tensor(
[[1.60887269e-05]
 [5.74600519e-05]
 [8.89112362e-05]
 [1.12529459e-04]
 [1.31422319e-04]
 [1.55989515e-04]
 [1.67429668e-04]
 [1.99670399e-04]
 [2.04122216e-04]
 [2.66792288e-04]
 [2.71672656e-04]
 [2.73035262e-04]
 [2.80554961e-04]
 [2.89788988e-04]
 [3.14948678e-04]
 [3.54447390e-04]
 [4.85090575e-04]
 [5.33834632e-04]
 [5.41210280e-04]
 [5.68477902e-04]
 [5.91179672e-04]
 [6.12080394e-04]
 [6.15613834e-04]
 [6.49063151e-04]
 [6.83088834e-04]
 [6.86966706e-04]
 [6.87106512e-04]
 [6.89389463e-04]
 [7.34040143e-04]
 [7.46424807e-04]
 [7.56519005e-04]
 [7.73126796e-04]
 [8.37119947e-04]
 [8.75153831e-04]
 [8.77210035e-04]
 [9.09702631e-04]
 [9.18352645e-04]
 [9.41572219e-04]
 [9.68209107e-04]
 [9.81127785e-04]
 [9.82320407e-04]
 [1.01772036e-03]
 [1.02902372e-03]
 [1.03257995e-03]
 [1.05272208e-03]
 [1.10470618e-03]
 [1.12028486e-03]
 [1.12357741e-03]
 [1.15369061e-03]
 [1.19346457e-03]
 [1.27674897e-03]
 [1.29224852e-03]
 [1.30595282e-03]
 [1.34399454e-03]
 [1.37182908e-03]

In [144]:
def init_model(num_hidden_layers=8, num_neurons_per_layer=20):
    # Initialize a feedforward neural network
    model = tf.keras.Sequential()

    # Input is one-dimensional (time)
    model.add(tf.keras.Input(1,))

    for _ in range(num_hidden_layers):
        model.add(tf.keras.layers.Dense(num_neurons_per_layer,
            activation=tf.keras.activations.get('tanh'),
            input_dim=t_data.shape[1],
            kernel_initializer='glorot_normal'))

    # Output is one-dimensional (center_a , center_b , R , theat_l , thetah_r)
    model.add(tf.keras.layers.Dense(5,))

    return model

62.46207348867272


tf.Tensor([[0.]], shape=(1, 1), dtype=float32)
tf.Tensor([[0. 0. 0. 0. 0.]], shape=(1, 5), dtype=float32)


In [145]:
# Output is one-dimensional (center_a , center_b , R , theta_l , theta_r)
def get_r(model, t_data):

    # A tf.GradientTape is used to compute derivatives in TensorFlow
    with tf.GradientTape(persistent=True) as tape:
        # Split t and x to compute partial derivatives
        t = t_data
        # Variables t are watched during tape
        tape.watch(t)

        # Determine residual
        u = model(t_data)
        a = tf.reshape(u[:,0],shape=(-1,1))
        b = tf.reshape(u[:,1],shape=(-1,1))
        R = tf.reshape(u[:,2],shape=(-1,1))
        theta_1 =tf.reshape(u[:,3],shape=(-1,1))
        theta_2 = tf.reshape(u[:,4],shape=(-1,1))


        #yl = R*tf.sin(theta_l)+b
        #yr = R*tf.sin(theta_r)+b
        area = cal_area(a,b,d,theta_1,theta_2,R)

    a_t = tape.gradient(a,t)
    b_t = tape.gradient(b,t)
    R_t = tape.gradient(R,t)
    theta_1_t = tape.gradient(theta_1,t)
    theta_2_t = tape.gradient(theta_2,t)

    area_t = tape.gradient(area, t)
    yl_t = R_t*tf.sin(theta_1)+R*tf.cos(theta_1)*theta_1_t +b_t
    yr_t = R_t*tf.sin(theta_2)+R*tf.cos(theta_2)*theta_2_t +b_t

    #print(yl_t)
    #print(yr_t)
    #print(area_t )

    del tape

    return fun_r(yl_t , yr_t ,vl ,vr,area_t)

In [104]:
model=  init_model()
print(model(t_data))

tf.Tensor(
[[-1.77238748e-07 -5.45751552e-07  6.33656288e-06  3.81527390e-06
  -3.93755490e-06]
 [-6.32998974e-07 -1.94912330e-06  2.26307049e-05  1.36260524e-05
  -1.40627726e-05]
 [-9.79475640e-07 -3.01599034e-06  3.50177885e-05  2.10843729e-05
  -2.17601352e-05]
 ...
 [-3.07150986e-04 -9.46135815e-04  1.09859100e-02  6.61490389e-03
  -6.82675899e-03]
 [-3.07451866e-04 -9.47063342e-04  1.09966810e-02  6.62138986e-03
  -6.83345239e-03]
 [-3.07542959e-04 -9.47344154e-04  1.09999420e-02  6.62335351e-03
  -6.83547884e-03]], shape=(1000, 5), dtype=float64)


In [105]:
print(get_r(init_model(), t_data))

tf.Tensor(
[[-0.6570471 ]
 [-0.65704727]
 [-0.6570474 ]
 [-0.6570475 ]
 [-0.65704758]
 [-0.65704768]
 [-0.65704773]
 [-0.65704786]
 [-0.65704788]
 [-0.65704813]
 [-0.65704815]
 [-0.65704816]
 [-0.65704819]
 [-0.65704823]
 [-0.65704833]
 [-0.65704848]
 [-0.657049  ]
 [-0.65704919]
 [-0.65704921]
 [-0.65704932]
 [-0.6570494 ]
 [-0.65704948]
 [-0.6570495 ]
 [-0.65704962]
 [-0.65704975]
 [-0.65704977]
 [-0.65704977]
 [-0.65704977]
 [-0.65704994]
 [-0.65704999]
 [-0.65705002]
 [-0.65705008]
 [-0.65705032]
 [-0.65705045]
 [-0.65705046]
 [-0.65705058]
 [-0.65705061]
 [-0.65705069]
 [-0.65705078]
 [-0.65705083]
 [-0.65705083]
 [-0.65705096]
 [-0.657051  ]
 [-0.65705101]
 [-0.65705108]
 [-0.65705126]
 [-0.65705131]
 [-0.65705132]
 [-0.65705142]
 [-0.65705156]
 [-0.65705184]
 [-0.65705189]
 [-0.65705193]
 [-0.65705206]
 [-0.65705214]
 [-0.65705222]
 [-0.65705231]
 [-0.65705232]
 [-0.65705242]
 [-0.65705256]
 [-0.65705281]
 [-0.65705296]
 [-0.65705297]
 [-0.65705297]
 [-0.65705308]
 [-0.65705313]

In [146]:
def compute_loss(model,t_data,initial_area): #initial_data = [a0 ,b0,r0 ,theta_l0,theta_r0 ]
    t_0 = tf.zeros((1,1))

    # Compute phi^r
    r = get_r(model, t_data)
    phi_r = tf.reduce_mean(tf.square(r))

    # Initialize loss
    #loss = phi_r

    # Add phi^0 and phi^b to the loss
    u = model(t_data)
    pred_a = tf.reshape(u[:,0],shape=(-1,1))
    pred_b = tf.reshape(u[:,1],shape=(-1,1))
    pred_R = tf.reshape(u[:,2],shape=(-1,1))
    pred_theta_1 =tf.reshape(u[:,3],shape=(-1,1))
    pred_theta_2 = tf.reshape(u[:,4],shape=(-1,1))
    pred_pred_area_0 = cal_area(pred_a,pred_b,d,pred_theta_1,pred_theta_2,pred_R)
    loss =phi_r+tf.reduce_mean(tf.square(pred_pred_area_0 -initial_area))


    # loss += tf.reduce_mean(tf.square(initial_data[0] - pred_a))
    # loss += tf.reduce_mean(tf.square(initial_data[1] - pred_b))
    # loss += tf.reduce_mean(tf.square(initial_data[2] - pred_R))
    # loss += tf.reduce_mean(tf.square(initial_data[3] - pred_theta_l))
    # loss += tf.reduce_mean(tf.square(initial_data[4] - pred_theta_r))

    return loss


In [147]:
t_0 = tf.zeros((1,1))
u = model(t_0)
pred_a = tf.reshape(u[:,0],shape=(-1,1))
pred_b = tf.reshape(u[:,1],shape=(-1,1))
pred_R = tf.reshape(u[:,2],shape=(-1,1))
pred_theta_1 =tf.reshape(u[:,3],shape=(-1,1))
pred_theta_2 = tf.reshape(u[:,4],shape=(-1,1))
pred_pred_area_0 = cal_area(pred_a,pred_b,d,pred_theta_1,pred_theta_2,pred_R)
loss =tf.reduce_mean(tf.square(pred_pred_area_0 -initial_area))
print(pred_pred_area_0 )

tf.Tensor([[0.00055253]], shape=(1, 1), dtype=float64)


In [148]:
def get_grad(model,t_data,initial_data):

    with tf.GradientTape(persistent=True) as tape:
        # This tape is for derivatives with
        # respect to trainable variables
        tape.watch(model.trainable_variables)
        loss = compute_loss(model,t_data,initial_data)

    g = tape.gradient(loss, model.trainable_variables)
    del tape

    return loss, g

In [149]:
# Initialize model aka u_\theta
model = init_model()

# We choose a piecewise decay of the learning rate, i.e., the
# step size in the gradient descent type algorithm
# the first 1000 steps use a learning rate of 0.01
# from 1000 - 3000: learning rate = 0.001
# from 3000 onwards: learning rate = 0.0005

lr = tf.keras.optimizers.schedules.PiecewiseConstantDecay([1000,3000],[1e-2,1e-3,5e-4])

# Choose the optimizer
optim = tf.keras.optimizers.Adam(learning_rate=lr)

In [113]:
print(model(tf.zeros((1,1)))[:,0])

tf.Tensor([0.], shape=(1,), dtype=float64)


In [150]:
from time import time

# Define one training step as a TensorFlow function to increase speed of training
@tf.function
def train_step(initial_data):
    # Compute current loss and gradient w.r.t. parameters
    loss, grad_theta = get_grad(model,t_data,initial_data)

    # Perform gradient descent step
    optim.apply_gradients(zip(grad_theta, model.trainable_variables))

    return loss

# Number of training epochs
N = 5000
hist = []

# Start timer
t0 = time()

for i in range(N+1):

    loss = train_step(initial_data)

    # Append current loss to hist
    hist.append(loss.numpy())

    # Output current loss after 50 iterates
    if i%50 == 0:
        print('It {:05d}: loss = {:10.8e}'.format(i,loss))

# Print computation time
print('\nComputation time: {} seconds'.format(time()-t0))

It 00000: loss = 1.50963558e+00
It 00050: loss = 6.00762909e-01
It 00100: loss = 6.00655545e-01
It 00150: loss = 6.00652789e-01
It 00200: loss = 6.00652736e-01
It 00250: loss = 6.00652735e-01
It 00300: loss = 6.00652735e-01
It 00350: loss = 6.00652735e-01
It 00400: loss = 6.00652735e-01
It 00450: loss = 6.00652735e-01
It 00500: loss = 6.00652735e-01
It 00550: loss = 6.00652735e-01
It 00600: loss = 6.00652735e-01
It 00650: loss = 6.00652735e-01
It 00700: loss = 6.00652735e-01
It 00750: loss = 6.00652735e-01
It 00800: loss = 6.00652735e-01
It 00850: loss = 6.00652735e-01
It 00900: loss = 6.00652735e-01
It 00950: loss = 6.00652735e-01
It 01000: loss = 6.00652735e-01
It 01050: loss = 6.00652735e-01
It 01100: loss = 6.00652735e-01
It 01150: loss = 6.00652735e-01
It 01200: loss = 6.00652735e-01
It 01250: loss = 6.00652735e-01
It 01300: loss = 6.00652735e-01
It 01350: loss = 6.00652735e-01
It 01400: loss = 6.00652735e-01
It 01450: loss = 6.00652735e-01
It 01500: loss = 6.00652735e-01
It 01550

KeyboardInterrupt: 

In [139]:
test_data=tf.linspace(0.0, 0.0280, 281)
test_data = tf.reshape(test_data,shape=(-1,1))
model(test_data)

<tf.Tensor: shape=(281, 5), dtype=float64, numpy=
array([[ 0.5492053 ,  0.09860509, -0.11922005, -0.41977698, -0.39738961],
       [ 0.54920127,  0.09860382, -0.11922209, -0.41977537, -0.39738614],
       [ 0.54919723,  0.09860256, -0.11922412, -0.41977375, -0.39738267],
       ...,
       [ 0.548058  ,  0.09824832, -0.1197829 , -0.41933273, -0.39642016],
       [ 0.54805378,  0.09824702, -0.11978491, -0.41933115, -0.39641666],
       [ 0.54804955,  0.09824572, -0.11978693, -0.41932957, -0.39641315]])>

In [21]:
u=model(tf.zeros((1,1)))
print(u)

tf.Tensor([[0. 0. 0. 0. 0.]], shape=(1, 5), dtype=float64)


In [17]:
u=model(t_data)

tf.Tensor(
[[-0.00128025 -0.00174529 -0.00076637  0.00199946  0.0022782 ]
 [-0.00140405 -0.00191405 -0.00084048  0.0021928   0.00249849]
 [-0.00150755 -0.00205515 -0.00090244  0.00235445  0.00268267]
 [-0.00151842 -0.00206998 -0.00090895  0.00237144  0.00270203]
 [-0.00164658 -0.00224468 -0.00098567  0.00257159  0.00293008]
 [-0.00259471 -0.00353726 -0.00155334  0.00405247  0.00461734]
 [-0.00261357 -0.00356297 -0.00156463  0.00408193  0.0046509 ]
 [-0.00301914 -0.00411589 -0.00180748  0.00471542  0.00537266]
 [-0.0030677  -0.0041821  -0.00183657  0.00479128  0.00545908]
 [-0.00427519 -0.00582838 -0.00255979  0.00667757  0.00760806]], shape=(10, 5), dtype=float64)


In [18]:
pred_a = tf.reshape(u[:,0],shape=(-1,1))
pred_b = tf.reshape(u[:,1],shape=(-1,1))
pred_R = tf.reshape(u[:,2],shape=(-1,1))
pred_theta_l =tf.reshape(u[:,3],shape=(-1,1))
pred_theta_r = tf.reshape(u[:,4],shape=(-1,1))

tf.Tensor(
[[-0.00128025]
 [-0.00140405]
 [-0.00150755]
 [-0.00151842]
 [-0.00164658]
 [-0.00259471]
 [-0.00261357]
 [-0.00301914]
 [-0.0030677 ]
 [-0.00427519]], shape=(10, 1), dtype=float64)
tf.Tensor(
[[-0.00174529]
 [-0.00191405]
 [-0.00205515]
 [-0.00206998]
 [-0.00224468]
 [-0.00353726]
 [-0.00356297]
 [-0.00411589]
 [-0.0041821 ]
 [-0.00582838]], shape=(10, 1), dtype=float64)
tf.Tensor(
[[-0.00076637]
 [-0.00084048]
 [-0.00090244]
 [-0.00090895]
 [-0.00098567]
 [-0.00155334]
 [-0.00156463]
 [-0.00180748]
 [-0.00183657]
 [-0.00255979]], shape=(10, 1), dtype=float64)
tf.Tensor(
[[0.00199946]
 [0.0021928 ]
 [0.00235445]
 [0.00237144]
 [0.00257159]
 [0.00405247]
 [0.00408193]
 [0.00471542]
 [0.00479128]
 [0.00667757]], shape=(10, 1), dtype=float64)
tf.Tensor(
[[0.0022782 ]
 [0.00249849]
 [0.00268267]
 [0.00270203]
 [0.00293008]
 [0.00461734]
 [0.0046509 ]
 [0.00537266]
 [0.00545908]
 [0.00760806]], shape=(10, 1), dtype=float64)


In [19]:
print(cal_area(pred_a,pred_b,d,pred_theta_l,pred_theta_r,pred_R))

tf.Tensor(
[[-5.60737359e-07]
 [-6.15036014e-07]
 [-6.60448071e-07]
 [-6.65221603e-07]
 [-7.21471872e-07]
 [-1.13843222e-06]
 [-1.14674044e-06]
 [-1.32562731e-06]
 [-1.34707061e-06]
 [-1.88217470e-06]], shape=(10, 1), dtype=float64)


In [ ]:
model = init_model()
t_0 = tf.zeros((1,1))
u=model(t_data)
print(u)
print(tf.reshape(u[:,0],shape=(-1,1)))
u = model(t_data)
a = tf.reshape(u[:,0],shape=(-1,1))
b = tf.reshape(u[:,1],shape=(-1,1))
R = tf.reshape(u[:,2],shape=(-1,1))
theta_l =tf.reshape(u[:,3],shape=(-1,1))
theta_r = tf.reshape(u[:,4],shape=(-1,1))
yl = R*tf.sin(theta_l)+b
yr = R*tf.sin(theta_r)+b
area = cal_area(a,b,d,theta_l,theta_r,R)
print(area)


In [ ]:
u=model(t_data)
print(u)
#print(t_data)
print(get_r(model, t_data))

In [ ]:
model = init_model()
t_0 = tf.zeros((1,1))
u=model(t_data)
print(u)
print(tf.reshape(u[:,0],shape=(-1,1)))
u = model(t_data)
a = tf.reshape(u[:,0],shape=(-1,1))
b = tf.reshape(u[:,1],shape=(-1,1))
R = tf.reshape(u[:,2],shape=(-1,1))
theta_l =tf.reshape(u[:,3],shape=(-1,1))
theta_r = tf.reshape(u[:,4],shape=(-1,1))
yl = R*tf.sin(theta_l)+b
yr = R*tf.sin(theta_r)+b
area = cal_area_theta(a,b,d,theta_l,theta_r,R)
print(area)

In [ ]:
model()